### ISSUE TITLE
GD-292: SimulateKeyPressed for SceneRunner not working

### ISSUE THREAD

**Issue by lbragile** [MikeSchulze/gdUnit4Mono#20]
**The used GdUnit4 version:**
https://github.com/MikeSchulze/gdUnit4/releases/tag/v4.2.0

**The used Godot version:**
Godot Engine v4.2.stable.mono.official.46dc27791

**OS including version:**
Vulkan API 1.3.242 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1650
Windows 10 - 10.0.19045 Build 19045

**Describe the bug**
First I show manual `Space`, which creates 2 nodes and passes.

Then I use the `SimulateKeyPressed` on the **SceneRunner** to automate the key press, which does not create a second node. Instead I see (*no focus set*):

```
ActivateTimeFactor: Engine.TimeScale=1, Engine.PhysicsTicksPerSecond=60
set time factor: 1
set physics iterations_per_second: 60
    no focus set
    process event <Node2D#81486939523> (PlayerTests) <- Space
    no focus set
    process event <Node2D#81486939523> (PlayerTests) <- Space
```

**Steps to Reproduce**
![gdunit4_tests](https://github.com/MikeSchulze/gdUnit4/assets/65437893/e6595b3a-651f-4288-9fcb-daa4b1cd7e78)

**Minimal reproduction project:**
N/A since project is currently private

**Comment by lbragile** [comment]
I believe you are correct, my issue still occurred when I moved the action handling logic to `_Input`. 

After more debugging, I figured out that it was due to not having nodes in a given group - thus skipping the "split" call. 
Ultimately this was caused by a deferred call to add the player node to a group in `_Ready()`.

More details:
```csharp
// scene script
public override void _Input(InputEvent @event)
{
	base._Input(@event);
	if (Input.IsActionJustReleased("Split"))
	{
		List<Player> players = GetTree().GetNodesInGroup(Level.instance.GroupName).Cast<Player>().ToList();

                // this was being skipped since players list was empty
		foreach (Player player in players)
		{
			player.Split();
		}
	}
}
```
```diff
// player script
public override void _Ready()
{
    base._Ready();
    
-    // this waits to add the player node to the group at the end of _Process frame
-    CallDeferred(Node.MethodName.AddToGroup, GroupName);
+  AddToGroup(GroupName);

    ...
}
```

I appreciate your help on this issue as I am new to Godot & C# in general.

**Comment by MikeSchulze** [comment]
Nice that we were able to narrow down the problem. Since the simulate function works as expected, I would now close the ticket as resolved.

Have fun with GdUnit4, I am always grateful for hints or suggestions for improvement
