### ISSUE TITLE
GD-21: Debugging via external editor is not currently possible

### ISSUE THREAD

**Issue by alexcodito** [MikeSchulze/gdUnit4Mono#21]
**The used Godot version:**

v4.2.stable.mono.official [46dc27791]

**OS including version:**

Windows 11 (10.0.22621 Build 22621)

**Describe the bug**
Debugger does not get attached and breakpoints are never triggered. Please note that regular in-game debugging via VS Code does work.

**Steps to Reproduce**
When setting a breakpoint in VS Code and subsequently pressing the debug button, the test runs but does not attach to the debugger.

![image](https://github.com/MikeSchulze/gdUnit4Mono/assets/22633561/66e25a11-8b50-4d09-a15c-a9acd97d5aed)

![image](https://github.com/MikeSchulze/gdUnit4Mono/assets/22633561/10b0c087-6350-477b-9ed5-b5303df25940)

![image](https://github.com/MikeSchulze/gdUnit4Mono/assets/22633561/fb8271c8-06be-4462-a56c-3715ad3edb50)

**Minimal reproduction project:**

```
using GdUnit4;
using System.Threading.Tasks;

[TestSuite]
public class prologue_test
{
    [TestCase]
    public async Task simulate_frame()
    {
        Assertions.AssertThat(true).IsTrue();
    }
}
```

**Comment by MikeSchulze** [comment]
Thanks for reporting.

Good news on the horizon, I will release the GdUnit4 test adapter for VS in the next few days.
There you will be able to run or debug selected tests.
![image](https://github.com/MikeSchulze/gdUnit4Mono/assets/347037/6774239a-f9be-4680-a9ec-ec31ecc7d547)

**Comment by alexcodito** [comment]
That's excellent, thank you for the update. And thanks for your hard work.

**Comment by GeorgeS2019** [comment]
@MikeSchulze 

Has this issue solved.

I debug within VS2022, using the TestAdaptor

However, I am not sure how to do that outside TestAdaptor

**Comment by MikeSchulze** [comment]
I will close it now, it is supposed to use the [gdunit4.test.adapter](https://github.com/MikeSchulze/gdUnit4Mono/blob/master/testadapter/README.md)
