### ISSUE TITLE
GD-22: Asserting on scene exceptions does not work

### ISSUE THREAD

**Issue by alexcodito** [MikeSchulze/gdUnit4Mono#22]
**The used Godot version:**
v4.2.stable.mono.official [46dc27791]

**OS including version:**
Windows 11 (10.0.22621 Build 22621)

**Describe the bug**
It is not possible to assert on exceptions that are thrown in a scene's script.

**Steps to Reproduce**

Given a blank/boilerplate .tscn scene with an attached script that contains the following method:
```
public void SomeMethodThatThrowsException()
{
    throw new System.Exception("Example message");
}
```

_Example test 1:_
```
[TestSuite]
public class prologue_test
{
    [TestCase]
    public async Task ExceptionIsThrown()
    {
        ISceneRunner runner = ISceneRunner.Load("res://Scenes/TestSceneWithException.tscn");

        var exception = GdUnit4.Assertions.AssertThrown(() =>
        {
            runner.Invoke("SomeMethodThatThrowsException");
        });

        exception.HasMessage("Example message");
    }
}
```
![image](https://github.com/MikeSchulze/gdUnit4Mono/assets/22633561/95730eca-38d4-4d23-b023-7584a4813077)

_Example test 2:_

```
using GdUnit4;
using System;
using System.Threading.Tasks;

[TestSuite]
public class prologue_test
{
    [TestCase]
    public async Task ExceptionIsThrown()
    {
        ISceneRunner runner = ISceneRunner.Load("res://Scenes/TestSceneWithException.tscn");
        Exception exception = null;

        try
        {
            runner.Invoke("SomeMethodThatThrowsException");
            var scene = runner.Scene();
            var variant = scene.Call("SomeMethodThatThrowsException");
        }
        catch (Exception ex)
        {
            exception = ex;
        }

        Assertions.AssertObject(exception).IsNotNull();
    }
}
```
![image](https://github.com/MikeSchulze/gdUnit4Mono/assets/22633561/cd1a4b39-e262-423a-8324-db1efed72fbb)

I appreciate that this may not be an issue with GdUnit4, as it almost seems like the exception is somehow being swallowed by the engine (though in which case, what is the purpose of the AssertThrown assertion?)

Please note that when running the game, I can see that the exception is thrown in the debugger window as expected (provided that I call the exception-throwing method).

Any advice would be appreciated.

**Comment by MikeSchulze** [comment]
Hm, that's strange, I need deeper investigation here.

From internal test coverage, it looks like is working
```
        [TestCase]
        public void DoAssertNotYetImplemented()
        {
            AssertThrown(() => AssertNotYetImplemented())
                .HasPropertyValue("LineNumber", 15)
                .HasMessage("Test not yet implemented!");
        }

```

**Comment by MikeSchulze** [comment]
So good news.
I was able to find the root cause and introduce a workaround, and also improved the `AssertThrown` functionality.
```
namespace GdUnit4.Tests.Core;

using System;

using static Assertions;

[TestSuite]
public class TestSuiteFailWithExceptions
{

    [TestCase]
    public void ExceptionIsThrownOnSceneInvoke()
    {
        var runner = ISceneRunner.Load("res://src/core/resources/scenes/TestSceneWithExceptionTest.tscn");

        AssertThrown(() => runner.Invoke("SomeMethodThatThrowsException"))
            .IsInstanceOf<InvalidOperationException>()
            .HasFileLineNumber(23)
            .HasFileName("src/core/resources/scenes/TestSceneWithExceptionTest.cs")
            .HasMessage("Test Exception");
    }
}
```
