### ISSUE TITLE
Get this error attempting to run SceneRunner in a new project

### ISSUE THREAD

**Issue by GeorgeS2019** [MikeSchulze/gdUnit4Mono#31]
![image](https://github.com/MikeSchulze/gdUnit4Mono/assets/49812372/d43fb6ca-a02e-4f8f-a1ec-cab0ed86cc5b)

**Comment by MikeSchulze** [comment]
Can you please add more description and details.

**Comment by GeorgeS2019** [comment]
I created a new Godot4 .NET project and attempted to figure out what settings needed to make gdUnit4Mono works as it should

 - by using AssetLib, I am able to install gdUnit4 addon and created a folder (test) where I put the test files.cs I found from https://github.com/MikeSchulze/gdUnit4Mono/tree/master/test/src/core

I tried to follow these settings to the new Godot4 .NET csproj

```
<Project Sdk="Godot.NET.Sdk/4.2.0">
  <PropertyGroup>
    <TargetFrameworks>net7.0</TargetFrameworks>
    <LangVersion>11.0</LangVersion>
    <!--Force nullable warnings, you can disable if you want-->
    <Nullable>enable</Nullable>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <!--Disable warning of invalid/incompatible GodotSharp version-->
    <NoWarn>NU1605</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <!--Required for GdUnit4-->
    <PackageReference Include="gdUnit4.api" Version="4.2.0-rc*" />
  </ItemGroup>
</Project>
```

The tests run, but no all pass. 

### ExampleTestSuite.cs

https://github.com/MikeSchulze/gdUnit4Mono/blob/master/test/src/core/ExampleTestSuite.cs


all 6 TestCase fail

```cs
        [TestCase(1, 2, 3, 6)]
        [TestCase(3, 4, 5, 12)]
        [TestCase(6, 7, 8, 21)]

        [TestCase(1, 2, 3, 6, TestName = "TestCaseA")]
        [TestCase(3, 4, 5, 12, TestName = "TestCaseB")]
        [TestCase(6, 7, 8, 21, TestName = "TestCaseC")]
```
```cs
using System.Threading.Tasks;

namespace GdUnit4.Tests.Core
{
    using static Assertions;
    using static Utils;

    [TestSuite]
    public class ExampleTestSuite
    {
        [Before]
        public void Before()
        {
            // GD.PrintS("calling Before");
        }

        [After]
        public void After()
        {
            //GD.PrintS("calling After");
        }

        [BeforeTest]
        public void BeforeTest()
        {
            //GD.PrintS("calling BeforeTest");
        }

        [AfterTest]
        public void AfterTest()
        {
            // GD.PrintS("calling AfterTest");
        }

        [TestCase]
        public void TestFoo()
        {
            AssertBool(true).IsEqual(true);
        }

        [TestCase]
        public void TestBar()
        {
            AssertBool(true).IsEqual(true);
        }

        [TestCase]
        public async Task Waiting()
        {
            await DoWait(200);
        }

        [TestCase]
        public void TestFooBar()
        {
            AssertBool(true).IsEqual(true);
        }

        [TestCase(1, 2, 3, 6)]
        [TestCase(3, 4, 5, 12)]
        [TestCase(6, 7, 8, 21)]
        public void TestCaseArguments(int a, int b, int c, int expect)
        {
            AssertThat(a + b + c).IsEqual(expect);
        }

        [TestCase(1, 2, 3, 6, TestName = "TestCaseA")]
        [TestCase(3, 4, 5, 12, TestName = "TestCaseB")]
        [TestCase(6, 7, 8, 21, TestName = "TestCaseC")]
        public void TestCasesWithCustomTestName(int a, double b, int c, int expect)
        {
            AssertThat(a + b + c).IsEqual(expect);
        }
    }
}
```


### SceneRunnerCSharpSceneTest.cs

These tests run within Godot, but all fail. I have corrected the godot path

![image](https://github.com/MikeSchulze/gdUnit4Mono/assets/49812372/3267c400-7b49-4135-acc6-f0704206c935)

**Comment by GeorgeS2019** [comment]
![image](https://github.com/MikeSchulze/gdUnit4Mono/assets/49812372/2bc96572-5e82-4956-868f-872d9578239a)


This error happens when I am trying to run SceneRunner from within VS2022, when not using the original project 

![image](https://github.com/MikeSchulze/gdUnit4Mono/assets/49812372/7203085f-72eb-4de1-8da8-7169d0713a18)


## Summary.

Tests run when using the provided project : **gdUnit4Test** works

![image](https://github.com/MikeSchulze/gdUnit4Mono/assets/49812372/1de324ff-bab8-4eb7-8f76-b663d990eff8)

When I tried to bring the test files from the project to a whole new project, I face with problems


gdUnit4Mono\api\src\core\execution\ExecutionTimeoutException.cs

e.g.   ExecutionTimeoutException are used in test but protected. 

```cs
            // AwaitOnSignal must fail after an maximum timeout of 500ms because no signal 'panel_color_change' with given args color=Yellow is emited
            await AssertThrown(SceneRunner.AwaitSignal(TestScene.SignalName.PanelColorChange, box1, Colors.Yellow).WithTimeout(700))
                .ContinueWith(result => result.Result?.IsInstanceOf<GdUnit4.Executions.ExecutionTimeoutException>().HasMessage("Assertion: Timed out after 700ms."));
```
            // verify the box is still green
            AssertObject(box1.Color).IsEqual(Colors.Green);

```cs
    internal sealed class ExecutionTimeoutException : System.Exception
    {
        public ExecutionTimeoutException(string message, int line) : base(message)
        {
            LineNumber = line;
        }

        public int LineNumber
        { get; private set; }
    }
```

**Comment by GeorgeS2019** [comment]
https://mikeschulze.github.io/gdUnit4/faq/C%23/

The information there may not be complete

**Comment by MikeSchulze** [comment]
First of all, thank you for the message.
But if you are using the master branch, it is not released!
This is also clearly stated in the README.md.
The master branch is currently in an invalid state because I had to test and change a lot with the new test adapter approach.

Development is currently paused as I am finalizing the release of gdUnit4 v4.2.1.

**If you have used the master, this ticket can be closed.**

**Comment by GeorgeS2019** [comment]
## suggestion

Create a bare minimum Godot4 .NET project with minimum settings and configurations and try to bring the test files from  **gdUnit4Test** to the new project to check if these tests run

In this way, you may discover **bugs**

**Comment by MikeSchulze** [comment]
> ## suggestion
> Create a bare minimum Godot4 .NET project with minimum settings and configurations and try to bring the test files from **gdUnit4Test** to the new project to check if these tests run
> 
> In this way, you may discover **bugs**

The [gdUnit4Test.csproj](https://github.com/MikeSchulze/gdUnit4Mono/blob/master/test/gdUnit4Test.csproj) is the project for integration testing.

The ci-pr workfloaw will run this project to ensure nothing is broken.
But as I have already mentioned, the master is currently 
is in an invalid state. I will probably work on it again next week. The goal is to release the test-adaper.

The C# API is currently not a high priority as there is no feedback on who is using it.

**Comment by GeorgeS2019** [comment]
Most of the youtube videos use gdUnit4 **GDScript**.

Once people understand how the test adapter will be a game changer for gdUnit4 .NET, more people will appreciate it. 

The reliability of SceneRunner is a much better experience than GodotXUnit.

**Comment by MikeSchulze** [comment]
> Most of the youtube videos use gdUnit4 **GDScript**.
> 
> Once people understand how the test adapter will be a game changer for gdUnit4 .NET, more people will appreciate it.
> 
> The reliability of SceneRunner is a much better experience than GodotXUnit.

Thank you ;)
Yes, the test adapter will be a game changer!
