### ISSUE TITLE
GD-35: Add example project and use gdunit4 NuGet packages

### ISSUE THREAD

**Issue by MikeSchulze** [MikeSchulze/gdUnit4Mono#35]
### Description
It would be good to show by an example project how to use the GdUnit4 C# API.

## AC
Add an example project which uses the NuGet packages
- gdUnit4.api
- gdUnit4.test.adapter

**Comment by GeorgeS2019** [comment]
using the [latest](https://github.com/MikeSchulze/gdUnit4Mono/pull/37) gdUnit4API **TestAdaptor** on VS2022

![Z0nhScGr3J](https://github.com/MikeSchulze/gdUnit4Mono/assets/49812372/7d2ed607-0750-4b6e-80f7-e5913aec040e)

**Comment by GeorgeS2019** [comment]
Porting old [gd3mono ](https://github.com/MikeSchulze/gdUnit3-examples/issues/1)test codes to gd4mono test codes

**Comment by MikeSchulze** [comment]
@GeorgeS2019 do not add such comment to closed issues!
Please open instead a new task, closed issues has the resolved/closed state and will not touch anymore.
