### ISSUE TITLE
GD-39: `CS0246: The type or namespace name 'GdUnit4' could not be found`

### ISSUE THREAD

**Issue by websterek** [MikeSchulze/gdUnit4Mono#39]
### The used GdUnit4 version

4.2.1 (Pre Release/Master branch)

### The used Godot version

v4.2.1 Mono

### Operating System

Windows 10

### Describe the bug

In last version (updated by the addon and/or right from AssetLib) using C# Mono build MSBuild return an errors:

- CS0246: The type or namespace name 'GdUnit4' could not be found (are you missing a using directive or an assembly reference?) \game\addons\gdUnit4\src\mono\GdUnit4CSharpApi.cs(4,7)
- CS0246: The type or namespace name 'GdUnit4' could not be found (are you missing a using directive or an assembly reference?) \game\addons\gdUnit4\src\mono\GdUnit4CSharpApi.cs(15,16)

### Steps to Reproduce

1. Install the addon in latest Godot Mono Build
2. Build Project

**Comment by websterek** [comment]
My dotnet list, only Godot Packages
```
   [net7.0]: 
   Top-level Package             Requested   Resolved
   > Godot.SourceGenerators      4.2.1       4.2.1
   > GodotSharp                  4.2.1       4.2.1
   > GodotSharpEditor            4.2.1       4.2.1
```

And initial Godot output:
```
Godot Engine v4.2.1.stable.mono.official (c) 2007-present Juan Linietsky, Ariel Manzur & Godot Contributors.
  modules/gltf/register_types.cpp:63 - Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.
  res://addons/gdUnit4/src/mono/GdUnit4CSharpApiLoader.gd:25 - Invalid call. Nonexistent function 'Version' in base 'CSharpScript'.
Loading GdUnit4 Plugin success
GdUnit4Mono Version  loaded.
GdUnit4: Can't establish server checked port: 31002, Error: Already in use
GdUnit4: Retry (0) ...
GdUnit4: Test server successfully started checked port: 31003
```

So looking at my packages list, I miss something on addon installation? I just install it from AssetLib and enable it in settings without additional steps.

**Comment by MikeSchulze** [comment]
Don't at the `gdUnit4.testadapter` it is not official released.
You have to follow the instruction [how-to-enable-c-test-support](https://mikeschulze.github.io/gdUnit4/faq/C%23/#how-to-enable-c-test-support)

**Comment by MikeSchulze** [comment]
@websterek please give me feedback when you have your project up and running.
I would like to close this topic because it looks like your project is configured incorrectly and it is not a bug.

**Comment by websterek** [comment]
Everything is ok, that was my fault, thanks!
