### ISSUE TITLE
GD-47: `gdunit4.test.adapter` Timeout when attempting to run tests on addon project using .NET 8.0

### ISSUE THREAD

**Issue by Pieeer1** [MikeSchulze/gdUnit4Mono#47]
**The used GdUnit4 version:**
    <PackageReference Include="gdUnit4.api" Version="4.2.1" />
    <PackageReference Include="gdUnit4.test.adapter" Version="1.0.0" />

**The used Godot version:**
<Project Sdk="Godot.NET.Sdk/4.2.1">

**OS including version:**
Windows 10

**Describe the bug**
When attempting to run or view unit tests on my addon project, I receive the following error:

```Failed to negotiate protocol, waiting for response timed out after 90 seconds. This may occur due to machine slowness, please set environment variable VSTEST_CONNECTION_TIMEOUT to increase timeout.```

**Steps to Reproduce**
1. Create a new Addons Project in Godot 4.2.1
2. Upgrade your solution to .NET 8.0
3. Add the following to the csproj:
```
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="$(MicrosoftSdkVersion)" />
    <PackageReference Include="gdUnit4.api" Version="4.2.1" />
    <PackageReference Include="gdUnit4.test.adapter" Version="1.0.0" />
```
4. Create a unit test. 
5. Build the solution
6. Error, and no tests appear in the test sln

**Minimal reproduction project:**

csproj:
```
<Project Sdk="Godot.NET.Sdk/4.2.1">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <PropertyGroup>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="icon.png" />
  </ItemGroup>
  <ItemGroup>
    <None Include=".runsettings" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="$(MicrosoftSdkVersion)" />
    <PackageReference Include="gdUnit4.api" Version="4.2.1" />
    <PackageReference Include="gdUnit4.test.adapter" Version="1.0.0" />
  </ItemGroup>
</Project>
```
.runsettings:
```
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
    <RunConfiguration>
        <ResultsDirectory>./TestResults</ResultsDirectory>
        <TargetFrameworkVersion>net8.0</TargetFrameworkVersion>
        <TestSessionTimeout>180000</TestSessionTimeout>
        <TreatNoTestsAsError>true</TreatNoTestsAsError>
    </RunConfiguration>

    <LoggerRunSettings>
        <Loggers>
            <Logger friendlyName="console" enabled="True">
                <Configuration>
                    <Verbosity>detailed</Verbosity>
                </Configuration>
            </Logger>
            <Logger friendlyName="html" enabled="True">
                <Configuration>
                    <LogFileName>test-result.html</LogFileName>
                </Configuration>
            </Logger>
            <Logger friendlyName="trx" enabled="True">
                <Configuration>
                    <LogFileName>test-result.trx</LogFileName>
                </Configuration>
            </Logger>
        </Loggers>
    </LoggerRunSettings>

    <GdUnit4>
        <Parameters></Parameters>
        <DisplayName>FullyQualifiedName</DisplayName>
    </GdUnit4>
</RunSettings>
```
FileStructure:
![image](https://github.com/MikeSchulze/gdUnit4Mono/assets/11530364/7fc5192f-cb96-4abd-808a-d9197519963c)

HelloWorld.cs:
```
using GdUnit4;
using static GdUnit4.Assertions;

namespace GodotVoipNet.Tests;

[TestSuite]
public class HelloWorld
{
    [TestCase]
    public void Test()
    {
        AssertBool(true).IsTrue();
    }
}

```
To my knowledge, I have followed the steps required to correctly install the api and the test explorer. Additionally, I have taken the .runtime file, and set my csproj according to the example. If I missed something here I would be happy to try it, but currently my tests are unable to run.

**Comment by MikeSchulze** [comment]
Thanks for reporting this issue.
Please attach the 'C# Dev Kit Test Explorer' logs you can find on Output.
![image](https://github.com/MikeSchulze/gdUnit4Mono/assets/347037/40b0f315-8e21-41c4-a0d1-f3f9842571b5)

The API and test adapter are build in .NET 7 maybe this could be the issue.
Can you please add your project to reproduce please.

**Comment by Pieeer1** [comment]
> Thanks for reporting this issue. Please attach the 'C# Dev Kit Test Explorer' logs you can find on Output. ![image](https://private-user-images.githubusercontent.com/347037/308448878-40b0f315-8e21-41c4-a0d1-f3f9842571b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMzMzMzUsIm5iZiI6MTcwOTEzMzAzNSwicGF0aCI6Ii8zNDcwMzcvMzA4NDQ4ODc4LTQwYjBmMzE1LThlMjEtNDFjNC1hMGQxLWYzZjk4NDI1NzFiNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyOFQxNTEwMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOTg5NjI4ZTAxNjM5ZjM3MDkwZTMxNzdjMzk1NjVlMjQ3OGE5ZDhhMzFiYmRjYTlhMzJmMjZkNzg1ZWQ3OWQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VVXtskseaZdwiP6zyJ75qyBWFLRNUFdGrZcK9K8Y-Ig)
> 
> Have you set the `MicrosoftSdkVersion` if not you need to specify a version e.g. `<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.9.0" />`
> 
> Which Godot Version you have used? The API and test adapter are build in .NET 7 maybe this could be the issue. Can you please add your project to reproduce please.

https://github.com/Pieeer1/GodotVoipNet/tree/upgrade-version <-- Here is a branch with the tests.
Godot 4.2.1
Eh i would doubt the .NET 7 -> 8 transition would cause issues there, I have had little to no compatibility issues in the past but maybe.

**Comment by MikeSchulze** [comment]
just add the logs please, i need more details

**Comment by Pieeer1** [comment]
The preconditions are specifically set in the readme for vscode development. Is there a method of configuring it for Visual Studio?

**Comment by MikeSchulze** [comment]
> The preconditions are specifically set in the readme for vscode development. Is there a method of configuring it for Visual Studio?

I have no Visual Studio installed, I suggest asking @GeorgeS2019 he was able to run tests inside Visual Studio. You can reach out on my discord server.
I'm also interested in how to setup Visual Studio to finally document it.

**Comment by Pieeer1** [comment]
> > The preconditions are specifically set in the readme for vscode development. Is there a method of configuring it for Visual Studio?
> 
> I have no Visual Studio installed, I suggest asking @GeorgeS2019 he was able to run tests inside Visual Studio. You can reach out on my discord server. I'm also interested in how to setup Visual Studio to finally document it.

I can reach out on discord if you can DM me a link, once we get it figured out I can document that process here.

**Comment by Pieeer1** [comment]
> * Open the exampleProject.csproj

Thanks for the quick response,

I may be misunderstanding the environment variable value to be set, after adding the path in my env vars I can get it to appear in the test explorer, but running the tests from that window has another error: 

`An exception occurred while invoking executor 'executor://gdunit4.testadapter/': Godot runtime is not set! Set env 'GODOT_BIN' is missing!`

![image](https://github.com/MikeSchulze/gdUnit4Mono/assets/11530364/4ac4c8a6-d04d-4bcf-8a9c-0c395ece5c20)
![image](https://github.com/MikeSchulze/gdUnit4Mono/assets/11530364/5c84af33-6e99-4043-bebe-5b758e252cc9)
![image](https://github.com/MikeSchulze/gdUnit4Mono/assets/11530364/f578a328-23f6-4c16-a567-ed90893ec947)


I attempted to do so with just the name of the exe, as well as the raw path.

**Comment by GeorgeS2019** [comment]
@Pieeer1 
Have you seen [this](https://github.com/Pieeer1/GodotVoipNet/issues/8#issuecomment-1970182471). I ran your project and it works!

I simply clone the branch
I already define GODOT_BIN
I build the project and the test appear. 

![image](https://github.com/Pieeer1/GodotVoipNet/assets/49812372/c6b5436c-2b63-4235-96ec-25406dcc01b2)

**Comment by Pieeer1** [comment]
Ok I got it to work. For anyone looking to do this in the future, adding GODOT_BIN to the environment variables of the .runsettings file did the trick.
![image](https://github.com/MikeSchulze/gdUnit4Mono/assets/11530364/60226311-1b16-447e-8be6-6099fe6494e4)

**Comment by MikeSchulze** [comment]
Nice, Good to hear that you got it up and running. I will add the info to the documentation.

Close it as clarified
